ALTER TABLE device_tokens
  ADD COLUMN IF NOT EXISTS notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS previews_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS quiet_hours_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS quiet_hours_start_minute INTEGER,
  ADD COLUMN IF NOT EXISTS quiet_hours_end_minute INTEGER,
  ADD COLUMN IF NOT EXISTS timezone TEXT;
