export interface NativeEmoji {
	name: string;
	char: string;
	keywords: string[];
}

export const NATIVE_EMOJI_COMMON: NativeEmoji[] = [
	// Smileys
	{ name: 'joy', char: '😂', keywords: ['face', 'cry', 'tears', 'laugh'] },
	{ name: 'sob', char: '😭', keywords: ['cry', 'sad', 'tear', 'weep'] },
	{ name: 'heart_eyes', char: '😍', keywords: ['love', 'face'] },
	{ name: 'rolling_on_the_floor_laughing', char: '🤣', keywords: ['rofl', 'laugh'] },
	{ name: 'smile', char: '😊', keywords: ['happy', 'face'] },
	{ name: 'sweat_smile', char: '😅', keywords: ['nervous', 'laugh'] },
	{ name: 'grin', char: '😁', keywords: ['happy', 'face'] },
	{ name: 'wink', char: '😉', keywords: ['flirt', 'face'] },
	{ name: 'blush', char: '😊', keywords: ['shy', 'face'] },
	{ name: 'yum', char: '😋', keywords: ['tongue', 'face'] },
	{ name: 'sunglasses', char: '😎', keywords: ['cool', 'face'] },
	{ name: 'nerd_face', char: '🤓', keywords: ['glasses', 'face'] },
	{ name: 'thinking', char: '🤔', keywords: ['think', 'hmm', 'face'] },
	{ name: 'neutral_face', char: '😐', keywords: ['meh', 'face'] },
	{ name: 'expressionless', char: '😑', keywords: ['blank', 'face'] },
	{ name: 'smirk', char: '😏', keywords: ['sly', 'face'] },
	{ name: 'unamused', char: '😒', keywords: ['side_eye', 'face'] },
	{ name: 'weary', char: '😩', keywords: ['tired', 'face'] },
	{ name: 'tired_face', char: '😫', keywords: ['exhausted', 'face'] },
	{ name: 'grimacing', char: '😬', keywords: ['awkward', 'face'] },
	{ name: 'relieved', char: '😌', keywords: ['calm', 'face'] },
	{ name: 'open_mouth', char: '😮', keywords: ['surprise', 'shock', 'face'] },
	{ name: 'astonished', char: '😲', keywords: ['amazed', 'face'] },
	{ name: 'flushed', char: '😳', keywords: ['blush', 'embarrassed', 'face'] },
	{ name: 'fearful', char: '😨', keywords: ['scared', 'face'] },
	{ name: 'cold_sweat', char: '😰', keywords: ['nervous', 'worried', 'face'] },
	{ name: 'cry', char: '😢', keywords: ['sad', 'tear', 'face'] },
	{ name: 'scream', char: '😱', keywords: ['shocked', 'face'] },
	{ name: 'angry', char: '😠', keywords: ['mad', 'face'] },
	{ name: 'rage', char: '😡', keywords: ['pissed', 'face'] },
	{ name: 'triumph', char: '😤', keywords: ['steam', 'face'] },
	{ name: 'sleeping', char: '😴', keywords: ['zzz', 'face'] },
	{ name: 'drooling_face', char: '🤤', keywords: ['drool', 'face'] },
	{ name: 'sleepy', char: '😪', keywords: ['tired', 'face'] },
	{ name: 'dizzy_face', char: '😵', keywords: ['dead', 'face'] },
	{ name: 'zipper_mouth_face', char: '🤐', keywords: ['silent', 'face'] },
	{ name: 'nauseated_face', char: '🤢', keywords: ['sick', 'vomit', 'face'] },
	{ name: 'sneezing_face', char: '🤧', keywords: ['achoo', 'face'] },
	{ name: 'face_with_thermometer', char: '🤒', keywords: ['sick', 'fever', 'face'] },
	{ name: 'face_with_head_bandage', char: '🤕', keywords: ['hurt', 'injured', 'face'] },
	{ name: 'money_mouth_face', char: '🤑', keywords: ['rich', 'cash', 'face'] },
	{ name: 'cowboy_hat_face', char: '🤠', keywords: ['yeehaw', 'face'] },
	{ name: 'clown_face', char: '🤡', keywords: ['face'] },
	{ name: 'nauseated_face', char: '🤢', keywords: ['sick', 'face'] },
	{ name: 'rofl', char: '🤣', keywords: ['laugh', 'face'] },
	{ name: 'slightly_smiling_face', char: '🙂', keywords: ['smile', 'face'] },
	{ name: 'upside_down_face', char: '🙃', keywords: ['silly', 'face'] },
	{ name: 'face_with_rolling_eyes', char: '🙄', keywords: ['eyeroll', 'face'] },
	{ name: 'hugging_face', char: '🤗', keywords: ['hug', 'face'] },
	{ name: 'star_struck', char: '🤩', keywords: ['eyes', 'face'] },
	{ name: 'shushing_face', char: '🤫', keywords: ['quiet', 'face'] },
	{ name: 'face_with_hand_over_mouth', char: '🤭', keywords: ['gasp', 'face'] },
	{ name: ' exploding_head', char: '🤯', keywords: ['mindblown', 'face'] },

	// People / Gestures
	{ name: '+1', char: '👍', keywords: ['thumbsup', 'agree', 'yes'] },
	{ name: '-1', char: '👎', keywords: ['thumbsdown', 'disagree', 'no'] },
	{ name: 'ok_hand', char: '👌', keywords: ['perfect', 'gesture'] },
	{ name: 'v', char: '✌️', keywords: ['peace', 'victory', 'gesture'] },
	{ name: 'crossed_fingers', char: '🤞', keywords: ['luck', 'gesture'] },
	{ name: 'raised_hand', char: '✋', keywords: ['stop', 'highfive', 'gesture'] },
	{ name: 'wave', char: '👋', keywords: ['hello', 'bye', 'gesture'] },
	{ name: 'point_up', char: '☝️', keywords: ['finger', 'gesture'] },
	{ name: 'point_up_2', char: '👆', keywords: ['finger', 'gesture'] },
	{ name: 'point_down', char: '👇', keywords: ['finger', 'gesture'] },
	{ name: 'point_left', char: '👈', keywords: ['finger', 'gesture'] },
	{ name: 'point_right', char: '👉', keywords: ['finger', 'gesture'] },
	{ name: 'muscle', char: '💪', keywords: ['strong', 'bicep', 'flex'] },
	{ name: 'pray', char: '🙏', keywords: ['please', 'thanks', 'pray'] },
	{ name: 'clap', char: '👏', keywords: ['applause', 'bravo'] },
	{ name: 'raised_hands', char: '🙌', keywords: ['celebrate', 'hooray'] },
	{ name: 'fist', char: '✊', keywords: ['punch', 'power'] },
	{ name: 'punch', char: '👊', keywords: ['fist', 'bro'] },
	{ name: 'handshake', char: '🤝', keywords: ['deal', 'agree'] },
	{ name: 'writing_hand', char: '✍️', keywords: ['write', 'pen'] },
	{ name: 'selfie', char: '🤳', keywords: ['camera', 'phone'] },
	{ name: 'nail_care', char: '💅', keywords: ['manicure', 'nails'] },
	{ name: 'ear', char: '👂', keywords: ['hear', 'listen'] },
	{ name: 'eyes', char: '👀', keywords: ['look', 'see', 'watch'] },
	{ name: 'eye', char: '👁️', keywords: ['look', 'see'] },
	{ name: 'tongue', char: '👅', keywords: ['lick', 'taste'] },
	{ name: 'lips', char: '👄', keywords: ['kiss', 'mouth'] },
	{ name: 'brain', char: '🧠', keywords: ['smart', 'think'] },
	{ name: 'heart', char: '❤️', keywords: ['love', 'like'] },
	{ name: 'orange_heart', char: '🧡', keywords: ['love'] },
	{ name: 'yellow_heart', char: '💛', keywords: ['love'] },
	{ name: 'green_heart', char: '💚', keywords: ['love'] },
	{ name: 'blue_heart', char: '💙', keywords: ['love'] },
	{ name: 'purple_heart', char: '💜', keywords: ['love'] },
	{ name: 'black_heart', char: '🖤', keywords: ['love', 'dark'] },
	{ name: 'broken_heart', char: '💔', keywords: ['sad', 'love'] },
	{ name: 'two_hearts', char: '💕', keywords: ['love'] },
	{ name: 'sparkling_heart', char: '💖', keywords: ['love'] },
	{ name: 'heartpulse', char: '💗', keywords: ['love'] },
	{ name: 'cupid', char: '💘', keywords: ['love', 'arrow'] },
	{ name: 'gift_heart', char: '💝', keywords: ['love', 'gift'] },
	{ name: 'revolving_hearts', char: '💞', keywords: ['love'] },
	{ name: 'heart_decoration', char: '💟', keywords: ['love'] },
	{ name: '100', char: '💯', keywords: ['perfect', 'score', 'hundred'] },
	{ name: 'fire', char: '🔥', keywords: ['hot', 'burn', 'lit'] },
	{ name: 'boom', char: '💥', keywords: ['explosion', 'blast'] },
	{ name: 'dizzy', char: '💫', keywords: ['star', 'sparkle'] },
];

export function searchNativeEmojiCommon(query: string): NativeEmoji[] {
	const q = query.toLowerCase();
	return NATIVE_EMOJI_COMMON.filter(
		(e) =>
			e.name.includes(q) || e.keywords.some((k) => k.includes(q))
	).slice(0, 50);
}
