export interface NativeEmoji {
	name: string;
	char: string;
	keywords: string[];
}

export const NATIVE_EMOJI: NativeEmoji[] = [
	// Smileys
	{ name: 'joy', char: '😂', keywords: ['face', 'cry', 'tears', 'laugh'] },
	{ name: 'sob', char: '😭', keywords: ['cry', 'sad', 'tear', 'weep'] },
	{ name: 'heart_eyes', char: '😍', keywords: ['love', 'face'] },
	{ name: 'rolling_on_the_floor_laughing', char: '🤣', keywords: ['rofl', 'laugh'] },
	{ name: 'smile', char: '😊', keywords: ['happy', 'face'] },
	{ name: 'sweat_smile', char: '😅', keywords: ['nervous', 'laugh'] },
	{ name: 'grin', char: '😁', keywords: ['happy', 'face'] },
	{ name: 'wink', char: '😉', keywords: ['flirt', 'face'] },
	{ name: 'blush', char: '😊', keywords: ['shy', 'face'] },
	{ name: 'yum', char: '😋', keywords: ['tongue', 'face'] },
	{ name: 'sunglasses', char: '😎', keywords: ['cool', 'face'] },
	{ name: 'nerd_face', char: '🤓', keywords: ['glasses', 'face'] },
	{ name: 'thinking', char: '🤔', keywords: ['think', 'hmm', 'face'] },
	{ name: 'neutral_face', char: '😐', keywords: ['meh', 'face'] },
	{ name: 'expressionless', char: '😑', keywords: ['blank', 'face'] },
	{ name: 'smirk', char: '😏', keywords: ['sly', 'face'] },
	{ name: 'unamused', char: '😒', keywords: ['side_eye', 'face'] },
	{ name: 'weary', char: '😩', keywords: ['tired', 'face'] },
	{ name: 'tired_face', char: '😫', keywords: ['exhausted', 'face'] },
	{ name: 'grimacing', char: '😬', keywords: ['awkward', 'face'] },
	{ name: 'relieved', char: '😌', keywords: ['calm', 'face'] },
	{ name: 'open_mouth', char: '😮', keywords: ['surprise', 'shock', 'face'] },
	{ name: 'astonished', char: '😲', keywords: ['amazed', 'face'] },
	{ name: 'flushed', char: '😳', keywords: ['blush', 'embarrassed', 'face'] },
	{ name: 'fearful', char: '😨', keywords: ['scared', 'face'] },
	{ name: 'cold_sweat', char: '😰', keywords: ['nervous', 'worried', 'face'] },
	{ name: 'cry', char: '😢', keywords: ['sad', 'tear', 'face'] },
	{ name: 'scream', char: '😱', keywords: ['shocked', 'face'] },
	{ name: 'angry', char: '😠', keywords: ['mad', 'face'] },
	{ name: 'rage', char: '😡', keywords: ['pissed', 'face'] },
	{ name: 'triumph', char: '😤', keywords: ['steam', 'face'] },
	{ name: 'sleeping', char: '😴', keywords: ['zzz', 'face'] },
	{ name: 'drooling_face', char: '🤤', keywords: ['drool', 'face'] },
	{ name: 'sleepy', char: '😪', keywords: ['tired', 'face'] },
	{ name: 'dizzy_face', char: '😵', keywords: ['dead', 'face'] },
	{ name: 'zipper_mouth_face', char: '🤐', keywords: ['silent', 'face'] },
	{ name: 'nauseated_face', char: '🤢', keywords: ['sick', 'vomit', 'face'] },
	{ name: 'sneezing_face', char: '🤧', keywords: ['achoo', 'face'] },
	{ name: 'face_with_thermometer', char: '🤒', keywords: ['sick', 'fever', 'face'] },
	{ name: 'face_with_head_bandage', char: '🤕', keywords: ['hurt', 'injured', 'face'] },
	{ name: 'money_mouth_face', char: '🤑', keywords: ['rich', 'cash', 'face'] },
	{ name: 'cowboy_hat_face', char: '🤠', keywords: ['yeehaw', 'face'] },
	{ name: 'clown_face', char: '🤡', keywords: ['face'] },
	{ name: 'nauseated_face', char: '🤢', keywords: ['sick', 'face'] },
	{ name: 'rofl', char: '🤣', keywords: ['laugh', 'face'] },
	{ name: 'slightly_smiling_face', char: '🙂', keywords: ['smile', 'face'] },
	{ name: 'upside_down_face', char: '🙃', keywords: ['silly', 'face'] },
	{ name: 'face_with_rolling_eyes', char: '🙄', keywords: ['eyeroll', 'face'] },
	{ name: 'hugging_face', char: '🤗', keywords: ['hug', 'face'] },
	{ name: 'star_struck', char: '🤩', keywords: ['eyes', 'face'] },
	{ name: 'shushing_face', char: '🤫', keywords: ['quiet', 'face'] },
	{ name: 'face_with_hand_over_mouth', char: '🤭', keywords: ['gasp', 'face'] },
	{ name: ' exploding_head', char: '🤯', keywords: ['mindblown', 'face'] },

	// People / Gestures
	{ name: '+1', char: '👍', keywords: ['thumbsup', 'agree', 'yes'] },
	{ name: '-1', char: '👎', keywords: ['thumbsdown', 'disagree', 'no'] },
	{ name: 'ok_hand', char: '👌', keywords: ['perfect', 'gesture'] },
	{ name: 'v', char: '✌️', keywords: ['peace', 'victory', 'gesture'] },
	{ name: 'crossed_fingers', char: '🤞', keywords: ['luck', 'gesture'] },
	{ name: 'raised_hand', char: '✋', keywords: ['stop', 'highfive', 'gesture'] },
	{ name: 'wave', char: '👋', keywords: ['hello', 'bye', 'gesture'] },
	{ name: 'point_up', char: '☝️', keywords: ['finger', 'gesture'] },
	{ name: 'point_up_2', char: '👆', keywords: ['finger', 'gesture'] },
	{ name: 'point_down', char: '👇', keywords: ['finger', 'gesture'] },
	{ name: 'point_left', char: '👈', keywords: ['finger', 'gesture'] },
	{ name: 'point_right', char: '👉', keywords: ['finger', 'gesture'] },
	{ name: 'muscle', char: '💪', keywords: ['strong', 'bicep', 'flex'] },
	{ name: 'pray', char: '🙏', keywords: ['please', 'thanks', 'pray'] },
	{ name: 'clap', char: '👏', keywords: ['applause', 'bravo'] },
	{ name: 'raised_hands', char: '🙌', keywords: ['celebrate', 'hooray'] },
	{ name: 'fist', char: '✊', keywords: ['punch', 'power'] },
	{ name: 'punch', char: '👊', keywords: ['fist', 'bro'] },
	{ name: 'handshake', char: '🤝', keywords: ['deal', 'agree'] },
	{ name: 'writing_hand', char: '✍️', keywords: ['write', 'pen'] },
	{ name: 'selfie', char: '🤳', keywords: ['camera', 'phone'] },
	{ name: 'nail_care', char: '💅', keywords: ['manicure', 'nails'] },
	{ name: 'ear', char: '👂', keywords: ['hear', 'listen'] },
	{ name: 'eyes', char: '👀', keywords: ['look', 'see', 'watch'] },
	{ name: 'eye', char: '👁️', keywords: ['look', 'see'] },
	{ name: 'tongue', char: '👅', keywords: ['lick', 'taste'] },
	{ name: 'lips', char: '👄', keywords: ['kiss', 'mouth'] },
	{ name: 'brain', char: '🧠', keywords: ['smart', 'think'] },
	{ name: 'heart', char: '❤️', keywords: ['love', 'like'] },
	{ name: 'orange_heart', char: '🧡', keywords: ['love'] },
	{ name: 'yellow_heart', char: '💛', keywords: ['love'] },
	{ name: 'green_heart', char: '💚', keywords: ['love'] },
	{ name: 'blue_heart', char: '💙', keywords: ['love'] },
	{ name: 'purple_heart', char: '💜', keywords: ['love'] },
	{ name: 'black_heart', char: '🖤', keywords: ['love', 'dark'] },
	{ name: 'broken_heart', char: '💔', keywords: ['sad', 'love'] },
	{ name: 'two_hearts', char: '💕', keywords: ['love'] },
	{ name: 'sparkling_heart', char: '💖', keywords: ['love'] },
	{ name: 'heartpulse', char: '💗', keywords: ['love'] },
	{ name: 'cupid', char: '💘', keywords: ['love', 'arrow'] },
	{ name: 'gift_heart', char: '💝', keywords: ['love', 'gift'] },
	{ name: 'revolving_hearts', char: '💞', keywords: ['love'] },
	{ name: 'heart_decoration', char: '💟', keywords: ['love'] },
	{ name: '100', char: '💯', keywords: ['perfect', 'score', 'hundred'] },
	{ name: 'fire', char: '🔥', keywords: ['hot', 'burn', 'lit'] },
	{ name: 'boom', char: '💥', keywords: ['explosion', 'blast'] },
	{ name: 'dizzy', char: '💫', keywords: ['star', 'sparkle'] },
	{ name: 'sweat_drops', char: '💦', keywords: ['water', 'splash'] },
	{ name: 'dash', char: '💨', keywords: ['wind', 'fast', 'run'] },
	{ name: 'hole', char: '🕳️', keywords: ['pit'] },
	{ name: 'bomb', char: '💣', keywords: ['explode'] },
	{ name: 'speech_balloon', char: '💬', keywords: ['chat', 'message'] },
	{ name: 'thought_balloon', char: '💭', keywords: ['think'] },
	{ name: 'zzz', char: '💤', keywords: ['sleep', 'tired'] },

	// Animals
	{ name: 'dog', char: '🐶', keywords: ['puppy', 'pet'] },
	{ name: 'cat', char: '🐱', keywords: ['kitten', 'pet'] },
	{ name: 'mouse', char: '🐭', keywords: ['rat'] },
	{ name: 'hamster', char: '🐹', keywords: ['pet'] },
	{ name: 'rabbit', char: '🐰', keywords: ['bunny'] },
	{ name: 'fox_face', char: '🦊', keywords: ['fox'] },
	{ name: 'bear', char: '🐻', keywords: ['teddy'] },
	{ name: 'panda_face', char: '🐼', keywords: ['panda'] },
	{ name: 'koala', char: '🐨', keywords: ['bear'] },
	{ name: 'tiger', char: '🐯', keywords: ['cat'] },
	{ name: 'lion', char: '🦁', keywords: ['cat'] },
	{ name: 'cow', char: '🐮', keywords: ['moo'] },
	{ name: 'pig', char: '🐷', keywords: ['oink'] },
	{ name: 'frog', char: '🐸', keywords: ['pepe'] },
	{ name: 'monkey_face', char: '🐵', keywords: ['monkey'] },
	{ name: 'see_no_evil', char: '🙈', keywords: ['monkey', 'hide'] },
	{ name: 'hear_no_evil', char: '🙉', keywords: ['monkey'] },
	{ name: 'speak_no_evil', char: '🙊', keywords: ['monkey', 'secret'] },
	{ name: 'monkey', char: '🐒', keywords: ['ape'] },
	{ name: 'chicken', char: '🐔', keywords: ['bird'] },
	{ name: 'penguin', char: '🐧', keywords: ['bird'] },
	{ name: 'bird', char: '🐦', keywords: ['tweet'] },
	{ name: 'eagle', char: '🦅', keywords: ['bird'] },
	{ name: 'duck', char: '🦆', keywords: ['bird'] },
	{ name: 'owl', char: '🦉', keywords: ['bird'] },
	{ name: 'bat', char: '🦇', keywords: ['vampire'] },
	{ name: 'wolf', char: '🐺', keywords: ['dog'] },
	{ name: 'boar', char: '🐗', keywords: ['pig'] },
	{ name: 'horse', char: '🐴', keywords: ['pony'] },
	{ name: 'unicorn', char: '🦄', keywords: ['magic'] },
	{ name: 'bee', char: '🐝', keywords: ['honey', 'bug'] },
	{ name: 'bug', char: '🐛', keywords: ['insect'] },
	{ name: 'butterfly', char: '🦋', keywords: ['insect'] },
	{ name: 'snail', char: '🐌', keywords: ['slow'] },
	{ name: 'shell', char: '🐚', keywords: ['sea'] },
	{ name: 'turtle', char: '🐢', keywords: ['slow'] },
	{ name: 'snake', char: '🐍', keywords: ['snek'] },
	{ name: 'lizard', char: '🦎', keywords: ['reptile'] },
	{ name: 'octopus', char: '🐙', keywords: ['sea'] },
	{ name: 'squid', char: '🦑', keywords: ['sea'] },
	{ name: 'shrimp', char: '🦐', keywords: ['sea'] },
	{ name: 'crab', char: '🦀', keywords: ['sea'] },
	{ name: 'fish', char: '🐟', keywords: ['sea'] },
	{ name: 'tropical_fish', char: '🐠', keywords: ['sea'] },
	{ name: 'blowfish', char: '🐡', keywords: ['sea'] },
	{ name: 'dolphin', char: '🐬', keywords: ['sea'] },
	{ name: 'shark', char: '🦈', keywords: ['sea'] },
	{ name: 'whale', char: '🐳', keywords: ['sea'] },
	{ name: 'crocodile', char: '🐊', keywords: ['reptile'] },
	{ name: 'leopard', char: '🐆', keywords: ['cat'] },
	{ name: 'zebra', char: '🦓', keywords: ['horse'] },
	{ name: 'gorilla', char: '🦍', keywords: ['ape'] },
	{ name: 'elephant', char: '🐘', keywords: ['big'] },
	{ name: 'rhinoceros', char: '🦏', keywords: ['big'] },
	{ name: 'camel', char: '🐪', keywords: ['desert'] },
	{ name: 'giraffe', char: '🦒', keywords: ['tall'] },
	{ name: 'dragon', char: '🐉', keywords: ['fantasy'] },
	{ name: 'dragon_face', char: '🐲', keywords: ['fantasy'] },

	// Food
	{ name: 'pizza', char: '🍕', keywords: ['food'] },
	{ name: 'burger', char: '🍔', keywords: ['food'] },
	{ name: 'fries', char: '🍟', keywords: ['food'] },
	{ name: 'hotdog', char: '🌭', keywords: ['food'] },
	{ name: 'taco', char: '🌮', keywords: ['food'] },
	{ name: 'burrito', char: '🌯', keywords: ['food'] },
	{ name: 'sandwich', char: '🥪', keywords: ['food'] },
	{ name: 'egg', char: '🥚', keywords: ['food'] },
	{ name: 'bacon', char: '🥓', keywords: ['food'] },
	{ name: 'pancakes', char: '🥞', keywords: ['food'] },
	{ name: 'salad', char: '🥗', keywords: ['food'] },
	{ name: 'spaghetti', char: '🍝', keywords: ['food'] },
	{ name: 'sushi', char: '🍣', keywords: ['food'] },
	{ name: 'ramen', char: '🍜', keywords: ['food', 'noodle'] },
	{ name: 'stew', char: '🍲', keywords: ['food'] },
	{ name: 'curry', char: '🍛', keywords: ['food'] },
	{ name: 'rice', char: '🍚', keywords: ['food'] },
	{ name: 'rice_ball', char: '🍙', keywords: ['food'] },
	{ name: 'dumpling', char: '🥟', keywords: ['food'] },
	{ name: 'cookie', char: '🍪', keywords: ['food'] },
	{ name: 'cake', char: '🎂', keywords: ['food', 'birthday'] },
	{ name: 'ice_cream', char: '🍦', keywords: ['food'] },
	{ name: 'donut', char: '🍩', keywords: ['food'] },
	{ name: 'chocolate_bar', char: '🍫', keywords: ['food'] },
	{ name: 'candy', char: '🍬', keywords: ['food'] },
	{ name: 'popcorn', char: '🍿', keywords: ['food'] },
	{ name: 'coffee', char: '☕', keywords: ['drink'] },
	{ name: 'tea', char: '🍵', keywords: ['drink'] },
	{ name: 'beer', char: '🍺', keywords: ['drink'] },
	{ name: 'beers', char: '🍻', keywords: ['drink', 'cheers'] },
	{ name: 'wine_glass', char: '🍷', keywords: ['drink'] },
	{ name: 'cocktail', char: '🍸', keywords: ['drink'] },
	{ name: 'tropical_drink', char: '🍹', keywords: ['drink'] },
	{ name: 'champagne', char: '🍾', keywords: ['drink', 'celebrate'] },
	{ name: 'sake', char: '🍶', keywords: ['drink'] },
	{ name: 'baby_bottle', char: '🍼', keywords: ['drink'] },
	{ name: 'cup_with_straw', char: '🥤', keywords: ['drink'] },

	// Activities
	{ name: 'soccer', char: '⚽', keywords: ['sport', 'football'] },
	{ name: 'basketball', char: '🏀', keywords: ['sport'] },
	{ name: 'football', char: '🏈', keywords: ['sport'] },
	{ name: 'baseball', char: '⚾', keywords: ['sport'] },
	{ name: 'tennis', char: '🎾', keywords: ['sport'] },
	{ name: 'volleyball', char: '🏐', keywords: ['sport'] },
	{ name: 'golf', char: '⛳', keywords: ['sport'] },
	{ name: 'trophy', char: '🏆', keywords: ['win', 'award'] },
	{ name: 'medal', char: '🏅', keywords: ['win', 'award'] },
	{ name: 'musical_note', char: '🎵', keywords: ['music'] },
	{ name: 'notes', char: '🎶', keywords: ['music'] },
	{ name: 'microphone', char: '🎤', keywords: ['sing', 'karaoke'] },
	{ name: 'headphones', char: '🎧', keywords: ['music'] },
	{ name: 'drum', char: '🥁', keywords: ['music'] },
	{ name: 'guitar', char: '🎸', keywords: ['music'] },
	{ name: 'game_die', char: '🎲', keywords: ['dice', 'random'] },
	{ name: 'dart', char: '🎯', keywords: ['bullseye'] },
	{ name: 'bowling', char: '🎳', keywords: ['sport'] },
	{ name: 'video_game', char: '🎮', keywords: ['gaming', 'controller'] },
	{ name: 'slot_machine', char: '🎰', keywords: ['gamble'] },
	{ name: 'ballet_shoes', char: '🩰', keywords: ['dance'] },
	{ name: 'running_shirt_with_sash', char: '🎽', keywords: ['sport'] },
	{ name: 'ticket', char: '🎫', keywords: ['event'] },
	{ name: 'clapper', char: '🎬', keywords: ['film', 'movie'] },
	{ name: 'art', char: '🎨', keywords: ['paint'] },
	{ name: 'performing_arts', char: '🎭', keywords: ['theater', 'drama'] },
	{ name: 'circus_tent', char: '🎪', keywords: ['carnival'] },
	{ name: 'joystick', char: '🕹️', keywords: ['game'] },
	{ name: 'flower_playing_cards', char: '🎴', keywords: ['card'] },

	// Travel
	{ name: 'rocket', char: '🚀', keywords: ['space', 'launch'] },
	{ name: 'airplane', char: '✈️', keywords: ['flight', 'travel'] },
	{ name: 'helicopter', char: '🚁', keywords: ['flight'] },
	{ name: 'train', char: '🚆', keywords: ['travel'] },
	{ name: 'bullettrain_side', char: '🚄', keywords: ['travel'] },
	{ name: 'metro', char: '🚇', keywords: ['travel'] },
	{ name: 'bus', char: '🚌', keywords: ['travel'] },
	{ name: 'taxi', char: '🚕', keywords: ['travel'] },
	{ name: 'car', char: '🚗', keywords: ['drive', 'travel'] },
	{ name: 'truck', char: '🚚', keywords: ['delivery'] },
	{ name: 'ship', char: '🚢', keywords: ['boat', 'travel'] },
	{ name: 'sailboat', char: '⛵', keywords: ['boat'] },
	{ name: 'anchor', char: '⚓', keywords: ['ship'] },
	{ name: 'fuelpump', char: '⛽', keywords: ['gas'] },
	{ name: 'construction', char: '🚧', keywords: ['roadwork'] },
	{ name: 'traffic_light', char: '🚦', keywords: ['stoplight'] },
	{ name: 'vertical_traffic_light', char: '🚥', keywords: ['stoplight'] },
	{ name: 'world_map', char: '🗺️', keywords: ['map'] },
	{ name: 'mountain_snow', char: '🏔️', keywords: ['mountain'] },
	{ name: 'camping', char: '🏕️', keywords: ['outdoor'] },
	{ name: 'beach_umbrella', char: '🏖️', keywords: ['beach'] },
	{ name: 'desert', char: '🏜️', keywords: ['dry'] },
	{ name: 'island', char: '🏝️', keywords: ['tropical'] },
	{ name: 'sunrise', char: '🌅', keywords: ['morning'] },
	{ name: 'sunrise_over_mountains', char: '🌄', keywords: ['morning'] },
	{ name: 'city_sunset', char: '🌇', keywords: ['evening'] },
	{ name: 'city_sunrise', char: '🌆', keywords: ['evening'] },
	{ name: 'night_with_stars', char: '🌃', keywords: ['night'] },
	{ name: 'milky_way', char: '🌌', keywords: ['space'] },
	{ name: 'stars', char: '🌠', keywords: ['shooting_star'] },
	{ name: 'fireworks', char: '🎆', keywords: ['celebrate'] },
	{ name: 'sparkler', char: '🎇', keywords: ['celebrate'] },
	{ name: 'rainbow', char: '🌈', keywords: ['pride'] },
	{ name: 'bridge_at_night', char: '🌉', keywords: ['night'] },
	{ name: 'foggy', char: '🌁', keywords: ['fog'] },
	{ name: 'ferris_wheel', char: '🎡', keywords: ['amusement'] },
	{ name: 'roller_coaster', char: '🎢', keywords: ['amusement'] },
	{ name: 'carousel_horse', char: '🎠', keywords: ['amusement'] },
	{ name: 'tokyo_tower', char: '🗼', keywords: ['landmark'] },
	{ name: 'statue_of_liberty', char: '🗽', keywords: ['landmark'] },
	{ name: 'maple_leaf', char: '🍁', keywords: ['leaf', 'canada'] },
	{ name: 'fallen_leaf', char: '🍂', keywords: ['leaf', 'autumn'] },
	{ name: 'leaves', char: '🍃', keywords: ['leaf', 'wind'] },
	{ name: 'palm_tree', char: '🌴', keywords: ['tropical'] },
	{ name: 'cactus', char: '🌵', keywords: ['desert'] },
	{ name: 'herb', char: '🌿', keywords: ['plant'] },
	{ name: 'shamrock', char: '☘️', keywords: ['clover', 'luck'] },
	{ name: 'four_leaf_clover', char: '🍀', keywords: ['luck'] },
	{ name: 'rose', char: '🌹', keywords: ['flower'] },
	{ name: 'sunflower', char: '🌻', keywords: ['flower'] },
	{ name: 'hibiscus', char: '🌺', keywords: ['flower'] },
	{ name: 'blossom', char: '🌼', keywords: ['flower'] },
	{ name: 'tulip', char: '🌷', keywords: ['flower'] },
	{ name: 'seedling', char: '🌱', keywords: ['plant', 'grow'] },
	{ name: 'evergreen_tree', char: '🌲', keywords: ['tree'] },
	{ name: 'deciduous_tree', char: '🌳', keywords: ['tree'] },
	{ name: 'mushroom', char: '🍄', keywords: ['fungus'] },
	{ name: 'chestnut', char: '🌰', keywords: ['nut'] },
	{ name: 'grapes', char: '🍇', keywords: ['fruit'] },
	{ name: 'melon', char: '🍈', keywords: ['fruit'] },
	{ name: 'watermelon', char: '🍉', keywords: ['fruit'] },
	{ name: 'tangerine', char: '🍊', keywords: ['fruit'] },
	{ name: 'lemon', char: '🍋', keywords: ['fruit'] },
	{ name: 'banana', char: '🍌', keywords: ['fruit'] },
	{ name: 'pineapple', char: '🍍', keywords: ['fruit'] },
	{ name: 'apple', char: '🍎', keywords: ['fruit'] },
	{ name: 'green_apple', char: '🍏', keywords: ['fruit'] },
	{ name: 'pear', char: '🍐', keywords: ['fruit'] },
	{ name: 'peach', char: '🍑', keywords: ['fruit'] },
	{ name: 'cherries', char: '🍒', keywords: ['fruit'] },
	{ name: 'strawberry', char: '🍓', keywords: ['fruit'] },
	{ name: 'kiwi_fruit', char: '🥝', keywords: ['fruit'] },
	{ name: 'avocado', char: '🥑', keywords: ['fruit'] },
	{ name: 'tomato', char: '🍅', keywords: ['vegetable'] },
	{ name: 'eggplant', char: '🍆', keywords: ['vegetable'] },
	{ name: 'corn', char: '🌽', keywords: ['vegetable'] },
	{ name: 'carrot', char: '🥕', keywords: ['vegetable'] },
	{ name: 'hot_pepper', char: '🌶️', keywords: ['spicy'] },
	{ name: 'cucumber', char: '🥒', keywords: ['vegetable'] },
	{ name: 'broccoli', char: '🥦', keywords: ['vegetable'] },
	{ name: 'garlic', char: '🧄', keywords: ['vegetable'] },
	{ name: 'onion', char: '🧅', keywords: ['vegetable'] },
	{ name: 'potato', char: '🥔', keywords: ['vegetable'] },
	{ name: 'sweet_potato', char: '🍠', keywords: ['vegetable'] },
	{ name: 'croissant', char: '🥐', keywords: ['food'] },
	{ name: 'bagel', char: '🥯', keywords: ['food'] },
	{ name: 'pretzel', char: '🥨', keywords: ['food'] },
	{ name: 'cheese', char: '🧀', keywords: ['food'] },
	{ name: 'meat_on_bone', char: '🍖', keywords: ['food'] },
	{ name: 'poultry_leg', char: '🍗', keywords: ['food'] },
	{ name: 'cut_of_meat', char: '🥩', keywords: ['food'] },
	{ name: 'bento', char: '🍱', keywords: ['food'] },
	{ name: 'oden', char: '🍢', keywords: ['food'] },
	{ name: 'dango', char: '🍡', keywords: ['food'] },
	{ name: 'fried_shrimp', char: '🍤', keywords: ['food'] },
	{ name: 'moon_cake', char: '🥮', keywords: ['food'] },
	{ name: 'fortune_cookie', char: '🥠', keywords: ['food'] },
	{ name: 'takeout_box', char: '🥡', keywords: ['food'] },
	{ name: 'crab', char: '🦀', keywords: ['food'] },
	{ name: 'lobster', char: '🦞', keywords: ['food'] },
	{ name: 'shrimp', char: '🦐', keywords: ['food'] },
	{ name: 'squid', char: '🦑', keywords: ['food'] },
	{ name: 'oyster', char: '🦪', keywords: ['food'] },
	{ name: 'icecream', char: '🍨', keywords: ['food'] },
	{ name: 'shaved_ice', char: '🍧', keywords: ['food'] },
	{ name: 'doughnut', char: '🍩', keywords: ['food'] },
	{ name: 'custard', char: '🍮', keywords: ['food'] },
	{ name: 'lollipop', char: '🍭', keywords: ['food'] },
	{ name: 'honey_pot', char: '🍯', keywords: ['food'] },
	{ name: 'baby_bottle', char: '🍼', keywords: ['drink'] },
	{ name: 'milk_glass', char: '🥛', keywords: ['drink'] },
	{ name: 'mate_drink', char: '🧉', keywords: ['drink'] },
	{ name: 'ice_skate', char: '⛸️', keywords: ['sport'] },
	{ name: 'fishing_pole_and_fish', char: '🎣', keywords: ['sport'] },
	{ name: 'running_shirt_with_sash', char: '🎽', keywords: ['sport'] },
	{ name: 'ski', char: '🎿', keywords: ['sport'] },
	{ name: 'sled', char: '🛷', keywords: ['sport'] },
	{ name: 'cricket_game', char: '🏏', keywords: ['sport'] },
	{ name: 'field_hockey', char: '🏑', keywords: ['sport'] },
	{ name: 'ice_hockey', char: '🏒', keywords: ['sport'] },
	{ name: 'lacrosse', char: '🥍', keywords: ['sport'] },
	{ name: 'ping_pong', char: '🏓', keywords: ['sport'] },
	{ name: 'badminton', char: '🏸', keywords: ['sport'] },
	{ name: 'boxing_glove', char: '🥊', keywords: ['sport'] },
	{ name: 'martial_arts_uniform', char: '🥋', keywords: ['sport'] },
	{ name: 'goal_net', char: '🥅', keywords: ['sport'] },
	{ name: 'flag_in_hole', char: '⛳', keywords: ['sport'] },
	{ name: 'ice_skate', char: '⛸️', keywords: ['sport'] },
	{ name: 'fishing_pole_and_fish', char: '🎣', keywords: ['sport'] },
	{ name: 'bow_and_arrow', char: '🏹', keywords: ['sport'] },
	{ name: 'amphora', char: '🏺', keywords: ['vase'] },

	// Objects / Symbols
	{ name: 'watch', char: '⌚', keywords: ['time'] },
	{ name: 'iphone', char: '📱', keywords: ['phone'] },
	{ name: 'computer', char: '💻', keywords: ['laptop'] },
	{ name: 'keyboard', char: '⌨️', keywords: ['type'] },
	{ name: 'desktop_computer', char: '🖥️', keywords: ['pc'] },
	{ name: 'printer', char: '🖨️', keywords: ['print'] },
	{ name: 'mouse_three_button', char: '🖱️', keywords: ['click'] },
	{ name: 'trackball', char: '🖲️', keywords: ['mouse'] },
	{ name: 'camera', char: '📷', keywords: ['photo'] },
	{ name: 'camera_with_flash', char: '📸', keywords: ['photo'] },
	{ name: 'video_camera', char: '📹', keywords: ['film'] },
	{ name: 'movie_camera', char: '🎥', keywords: ['film'] },
	{ name: 'projector', char: '📽️', keywords: ['film'] },
	{ name: 'tv', char: '📺', keywords: ['television'] },
	{ name: 'radio', char: '📻', keywords: ['music'] },
	{ name: 'pager', char: '📟', keywords: ['old'] },
	{ name: 'fax', char: '📠', keywords: ['old'] },
	{ name: 'hourglass', char: '⌛', keywords: ['time'] },
	{ name: 'alarm_clock', char: '⏰', keywords: ['time', 'wake'] },
	{ name: 'stopwatch', char: '⏱️', keywords: ['time'] },
	{ name: 'timer_clock', char: '⏲️', keywords: ['time'] },
	{ name: 'mantelpiece_clock', char: '🕰️', keywords: ['time'] },
	{ name: 'bulb', char: '💡', keywords: ['idea', 'light'] },
	{ name: 'flashlight', char: '🔦', keywords: ['light'] },
	{ name: 'candle', char: '🕯️', keywords: ['light'] },
	{ name: 'wastebasket', char: '🗑️', keywords: ['trash'] },
	{ name: 'oil_drum', char: '🛢️', keywords: ['oil'] },
	{ name: 'money_with_wings', char: '💸', keywords: ['cash', 'fly'] },
	{ name: 'dollar', char: '💵', keywords: ['money'] },
	{ name: 'yen', char: '💴', keywords: ['money'] },
	{ name: 'euro', char: '💶', keywords: ['money'] },
	{ name: 'pound', char: '💷', keywords: ['money'] },
	{ name: 'credit_card', char: '💳', keywords: ['money'] },
	{ name: 'gem', char: '💎', keywords: ['diamond'] },
	{ name: 'scales', char: '⚖️', keywords: ['balance'] },
	{ name: 'wrench', char: '🔧', keywords: ['tool'] },
	{ name: 'hammer', char: '🔨', keywords: ['tool'] },
	{ name: 'pick', char: '⛏️', keywords: ['tool'] },
	{ name: 'nut_and_bolt', char: '🔩', keywords: ['tool'] },
	{ name: 'gear', char: '⚙️', keywords: ['settings'] },
	{ name: 'chains', char: '⛓️', keywords: ['link'] },
	{ name: 'gun', char: '🔫', keywords: ['shoot'] },
	{ name: 'bomb', char: '💣', keywords: ['explode'] },
	{ name: 'knife', char: '🔪', keywords: ['cut'] },
	{ name: 'shield', char: '🛡️', keywords: ['protect'] },
	{ name: 'smoking', char: '🚬', keywords: ['cigarette'] },
	{ name: 'coffin', char: '⚰️', keywords: ['dead'] },
	{ name: 'urn', char: '⚱️', keywords: ['ashes'] },
	{ name: 'crystal_ball', char: '🔮', keywords: ['magic'] },
	{ name: 'shopping_cart', char: '🛒', keywords: ['buy'] },
	{ name: 'balloon', char: '🎈', keywords: ['party'] },
	{ name: 'tada', char: '🎉', keywords: ['party', 'celebrate'] },
	{ name: 'confetti_ball', char: '🎊', keywords: ['party'] },
	{ name: 'scroll', char: '📜', keywords: ['document'] },
	{ name: 'page_with_curl', char: '📃', keywords: ['document'] },
	{ name: 'bookmark_tabs', char: '📑', keywords: ['mark'] },
	{ name: 'bar_chart', char: '📊', keywords: ['graph'] },
	{ name: 'chart_with_upwards_trend', char: '📈', keywords: ['graph', 'growth'] },
	{ name: 'chart_with_downwards_trend', char: '📉', keywords: ['graph', 'decline'] },
	{ name: 'date', char: '📅', keywords: ['calendar'] },
	{ name: 'calendar', char: '📆', keywords: ['schedule'] },
	{ name: 'spiral_calendar', char: '🗓️', keywords: ['schedule'] },
	{ name: 'card_index', char: '📇', keywords: ['rolodex'] },
	{ name: 'clipboard', char: '📋', keywords: ['copy'] },
	{ name: 'pushpin', char: '📌', keywords: ['pin'] },
	{ name: 'round_pushpin', char: '📍', keywords: ['pin'] },
	{ name: 'paperclip', char: '📎', keywords: ['attach'] },
	{ name: 'link', char: '🔗', keywords: ['url'] },
	{ name: 'mag', char: '🔍', keywords: ['search'] },
	{ name: 'mag_right', char: '🔎', keywords: ['search'] },
	{ name: 'lock', char: '🔒', keywords: ['secure'] },
	{ name: 'unlock', char: '🔓', keywords: ['open'] },
	{ name: 'closed_lock_with_key', char: '🔐', keywords: ['secure'] },
	{ name: 'key', char: '🔑', keywords: ['password'] },
	{ name: 'hammer_and_pick', char: '⚒️', keywords: ['tool'] },
	{ name: 'alembic', char: '⚗️', keywords: ['science'] },
	{ name: 'gear', char: '⚙️', keywords: ['settings'] },
	{ name: 'atom_symbol', char: '⚛️', keywords: ['science'] },
	{ name: 'fleur_de_lis', char: '⚜️', keywords: ['scout'] },
	{ name: 'warning', char: '⚠️', keywords: ['alert', 'caution'] },
	{ name: 'children_crossing', char: '🚸', keywords: ['school'] },
	{ name: 'beginner', char: '🔰', keywords: ['new'] },
	{ name: 'o', char: '⭕', keywords: ['circle'] },
	{ name: 'white_check_mark', char: '✅', keywords: ['done', 'check'] },
	{ name: 'ballot_box_with_check', char: '☑️', keywords: ['vote'] },
	{ name: 'heavy_check_mark', char: '✔️', keywords: ['check'] },
	{ name: 'heavy_multiplication_x', char: '✖️', keywords: ['x'] },
	{ name: 'x', char: '❌', keywords: ['cross'] },
	{ name: 'negative_squared_cross_mark', char: '❎', keywords: ['no'] },
	{ name: 'heavy_plus_sign', char: '➕', keywords: ['plus'] },
	{ name: 'heavy_minus_sign', char: '➖', keywords: ['minus'] },
	{ name: 'heavy_division_sign', char: '➗', keywords: ['divide'] },
	{ name: 'curly_loop', char: '➰', keywords: ['loop'] },
	{ name: 'loop', char: '➿', keywords: ['loop'] },
	{ name: 'part_alternation_mark', char: '〽️', keywords: ['mark'] },
	{ name: 'eight_spoked_asterisk', char: '✳️', keywords: ['star'] },
	{ name: 'eight_pointed_black_star', char: '✴️', keywords: ['star'] },
	{ name: 'sparkle', char: '❇️', keywords: ['sparkle'] },
	{ name: 'copyright', char: '©️', keywords: ['copy'] },
	{ name: 'registered', char: '®️', keywords: ['register'] },
	{ name: 'tm', char: '™️', keywords: ['trademark'] },
	{ name: 'hash', char: '#️⃣', keywords: ['number'] },
	{ name: 'asterisk', char: '*️⃣', keywords: ['star'] },
	{ name: 'zero', char: '0️⃣', keywords: ['number'] },
	{ name: 'one', char: '1️⃣', keywords: ['number'] },
	{ name: 'two', char: '2️⃣', keywords: ['number'] },
	{ name: 'three', char: '3️⃣', keywords: ['number'] },
	{ name: 'four', char: '4️⃣', keywords: ['number'] },
	{ name: 'five', char: '5️⃣', keywords: ['number'] },
	{ name: 'six', char: '6️⃣', keywords: ['number'] },
	{ name: 'seven', char: '7️⃣', keywords: ['number'] },
	{ name: 'eight', char: '8️⃣', keywords: ['number'] },
	{ name: 'nine', char: '9️⃣', keywords: ['number'] },
	{ name: 'ten', char: '🔟', keywords: ['number'] },
	{ name: 'capital_abcd', char: '🔠', keywords: ['letters'] },
	{ name: 'abcd', char: '🔡', keywords: ['letters'] },
	{ name: 'symbols', char: '🔣', keywords: ['signs'] },
	{ name: 'abc', char: '🔤', keywords: ['letters'] },
	{ name: 'a', char: '🅰️', keywords: ['blood'] },
	{ name: 'ab', char: '🆎', keywords: ['blood'] },
	{ name: 'b', char: '🅱️', keywords: ['blood'] },
	{ name: 'cl', char: '🆑', keywords: ['clear'] },
	{ name: 'cool', char: '🆒', keywords: ['awesome'] },
	{ name: 'free', char: '🆓', keywords: ['no_charge'] },
	{ name: 'information_source', char: 'ℹ️', keywords: ['info'] },
	{ name: 'id', char: '🆔', keywords: ['identity'] },
	{ name: 'm', char: 'Ⓜ️', keywords: ['metro'] },
	{ name: 'new', char: '🆕', keywords: ['fresh'] },
	{ name: 'ng', char: '🆖', keywords: ['no_good'] },
	{ name: 'o2', char: '🅾️', keywords: ['blood'] },
	{ name: 'ok', char: '🆗', keywords: ['okay'] },
	{ name: 'parking', char: '🅿️', keywords: ['park'] },
	{ name: 'sos', char: '🆘', keywords: ['help'] },
	{ name: 'up', char: '🆙', keywords: ['up'] },
	{ name: 'vs', char: '🆚', keywords: ['versus'] },
	{ name: 'koko', char: '🈁', keywords: ['japanese'] },
	{ name: 'sa', char: '🈂️', keywords: ['japanese'] },
	{ name: 'u6708', char: '🈷️', keywords: ['japanese'] },
	{ name: 'u6709', char: '🈶', keywords: ['japanese'] },
	{ name: 'u6307', char: '🈯', keywords: ['japanese'] },
	{ name: 'ideograph_advantage', char: '🉐', keywords: ['japanese'] },
	{ name: 'u5272', char: '🈹', keywords: ['japanese'] },
	{ name: 'u7121', char: '🈚', keywords: ['japanese'] },
	{ name: 'u7981', char: '🈲', keywords: ['japanese'] },
	{ name: 'accept', char: '🉑', keywords: ['japanese'] },
	{ name: 'u7533', char: '🈸', keywords: ['japanese'] },
	{ name: 'u5408', char: '🈴', keywords: ['japanese'] },
	{ name: 'u7a7a', char: '🈳', keywords: ['japanese'] },
	{ name: 'congratulations', char: '㊗️', keywords: ['japanese'] },
	{ name: 'secret', char: '㊙️', keywords: ['japanese'] },
	{ name: 'u55b6', char: '🈺', keywords: ['japanese'] },
	{ name: 'u6e80', char: '🈵', keywords: ['japanese'] },
	{ name: 'red_circle', char: '🔴', keywords: ['circle'] },
	{ name: 'blue_circle', char: '🔵', keywords: ['circle'] },
	{ name: 'black_circle', char: '⚫', keywords: ['circle'] },
	{ name: 'white_circle', char: '⚪', keywords: ['circle'] },
	{ name: 'black_large_square', char: '⬛', keywords: ['square'] },
	{ name: 'white_large_square', char: '⬜', keywords: ['square'] },
	{ name: 'black_medium_square', char: '◼️', keywords: ['square'] },
	{ name: 'white_medium_square', char: '◻️', keywords: ['square'] },
	{ name: 'black_medium_small_square', char: '◾', keywords: ['square'] },
	{ name: 'white_medium_small_square', char: '◽', keywords: ['square'] },
	{ name: 'black_small_square', char: '▪️', keywords: ['square'] },
	{ name: 'white_small_square', char: '▫️', keywords: ['square'] },
	{ name: 'large_orange_diamond', char: '🔶', keywords: ['diamond'] },
	{ name: 'large_blue_diamond', char: '🔷', keywords: ['diamond'] },
	{ name: 'small_orange_diamond', char: '🔸', keywords: ['diamond'] },
	{ name: 'small_blue_diamond', char: '🔹', keywords: ['diamond'] },
	{ name: 'small_red_triangle', char: '🔺', keywords: ['triangle'] },
	{ name: 'small_red_triangle_down', char: '🔻', keywords: ['triangle'] },
	{ name: 'diamond_shape_with_a_dot_inside', char: '💠', keywords: ['diamond'] },
	{ name: 'radio_button', char: '🔘', keywords: ['circle'] },
	{ name: 'white_square_button', char: '🔳', keywords: ['square'] },
	{ name: 'black_square_button', char: '🔲', keywords: ['square'] },

	// Clocks
	{ name: 'clock1', char: '🕐', keywords: ['time'] },
	{ name: 'clock2', char: '🕑', keywords: ['time'] },
	{ name: 'clock3', char: '🕒', keywords: ['time'] },
	{ name: 'clock4', char: '🕓', keywords: ['time'] },
	{ name: 'clock5', char: '🕔', keywords: ['time'] },
	{ name: 'clock6', char: '🕕', keywords: ['time'] },
	{ name: 'clock7', char: '🕖', keywords: ['time'] },
	{ name: 'clock8', char: '🕗', keywords: ['time'] },
	{ name: 'clock9', char: '🕘', keywords: ['time'] },
	{ name: 'clock10', char: '🕙', keywords: ['time'] },
	{ name: 'clock11', char: '🕚', keywords: ['time'] },
	{ name: 'clock12', char: '🕛', keywords: ['time'] },
	{ name: 'clock130', char: '🕜', keywords: ['time'] },
	{ name: 'clock230', char: '🕝', keywords: ['time'] },
	{ name: 'clock330', char: '🕞', keywords: ['time'] },
	{ name: 'clock430', char: '🕟', keywords: ['time'] },
	{ name: 'clock530', char: '🕠', keywords: ['time'] },
	{ name: 'clock630', char: '🕡', keywords: ['time'] },
	{ name: 'clock730', char: '🕢', keywords: ['time'] },
	{ name: 'clock830', char: '🕣', keywords: ['time'] },
	{ name: 'clock930', char: '🕤', keywords: ['time'] },
	{ name: 'clock1030', char: '🕥', keywords: ['time'] },
	{ name: 'clock1130', char: '🕦', keywords: ['time'] },
	{ name: 'clock1230', char: '🕧', keywords: ['time'] },

	// Flags (subset)
	{ name: 'white_flag', char: '🏳️', keywords: ['surrender'] },
	{ name: 'black_flag', char: '🏴', keywords: ['pirate'] },
	{ name: 'checkered_flag', char: '🏁', keywords: ['race'] },
	{ name: 'triangular_flag_on_post', char: '🚩', keywords: ['mark'] },
	{ name: 'rainbow_flag', char: '🏳️‍🌈', keywords: ['pride'] },
	{ name: 'pirate_flag', char: '🏴‍☠️', keywords: ['skull'] },
];

export function searchNativeEmoji(query: string): NativeEmoji[] {
	const q = query.toLowerCase();
	return NATIVE_EMOJI.filter(
		(e) =>
			e.name.includes(q) || e.keywords.some((k) => k.includes(q))
	).slice(0, 50);
}
