/**
 * Media Upload E2E
 * Tests that a user can upload an image and video to a chat.
 *
 * TODO: Selectors need runtime verification against actual UI.
 * This test was generated by agent swarm; run and fix selectors before enabling in CI.
 */
import { test, expect, type Page } from '@playwright/test';
import { registerUser } from './utils';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function enterGeneralChat(page: Page) {
	await expect(async () => {
		await page.getByRole('button', { name: 'Open chat General' }).click();
		await expect(page).toHaveURL(/\/chat\/.+/, { timeout: 1000 });
	}).toPass({ timeout: 5000 });
}

test.describe('Media Upload', () => {
	test('user can upload an image to a chat', async ({ page }) => {
		const username = `img_${Date.now()}`;
		await registerUser(page, username);
		await enterGeneralChat(page);

		// Click attach and select image file
		const [fileChooser] = await Promise.all([
			page.waitForEvent('filechooser'),
			page.getByRole('button', { name: 'Attach media' }).click()
		]);
		await fileChooser.setFiles(path.join(__dirname, 'fixtures', 'test-image.png'));

		// Wait a tick for Svelte state to propagate
		await page.waitForTimeout(200);

		// Image preview should appear
		await expect(page.locator('.file-preview .preview-img')).toBeVisible({ timeout: 3000 });

		// Send
		await page.getByRole('button', { name: 'Send message' }).click();

		// Image should appear inline in chat
		await expect(page.locator('.msg.own .media-image')).toBeVisible({ timeout: 10000 });
	});

	test('user can upload a video to a chat', async ({ page }) => {
		const username = `vid_${Date.now()}`;
		await registerUser(page, username);
		await enterGeneralChat(page);

		// Click attach and select video file
		const [fileChooser] = await Promise.all([
			page.waitForEvent('filechooser'),
			page.getByRole('button', { name: 'Attach media' }).click()
		]);
		await fileChooser.setFiles(path.join(__dirname, 'fixtures', 'test-video.mp4'));

		// Wait a tick for Svelte state to propagate
		await page.waitForTimeout(200);

		// File name should appear (video doesn't get image preview)
		await expect(page.locator('.file-preview .file-name')).toBeVisible({ timeout: 3000 });

		// Send
		await page.getByRole('button', { name: 'Send message' }).click();

		// Video should appear inline with controls (play button)
		const video = page.locator('.msg.own .media-video');
		await expect(video).toBeVisible({ timeout: 10000 });
		await expect(video).toHaveAttribute('controls');
	});
});
